indent_style = "Block"

blank_lines_lower_bound = 1
blank_lines_upper_bound = 1

edition = "2021"

fn_args_layout = "Vertical"
imports_layout = "Vertical"

reorder_impl_items = true

struct_field_align_threshold = 20

struct_lit_single_line = false

trailing_comma = "Never"

trailing_semicolon = true

use_field_init_shorthand = true

where_single_line = true

wrap_comments = true
newline_style = "Unix"
normalize_comments = true

reorder_imports = false
reorder_modules = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

force_multiline_blocks = true

max_width = 60

use_small_heuristics = "Max"

unstable_features = true